export const PRODUCT_CATALOG = [
  {
    id: "BC-02",
    name: "最美四百公里",
    liveMatchKeywords: ["最美四百公里"],
    line: "冰川环线",
    route: "波波来波达",
    destination: "glacier",
    destinationLabel: "林芝 / 冰川",
    destinationPriority: "core",
    destinations: ["林芝", "波密", "来古", "南迦巴瓦"],
    nights: 5,
    forms: ["自由行"],
    tags: ["自然", "风景", "冰川", "经典", "轻松"],
    intensity: "light",
    familyFriendly: true,
    elderFriendly: false,
    foreignerReady: true,
    seasonMonths: [3, 4, 5, 6, 7, 8, 9, 10],
    description: "林芝自由行里最容易成交的经典线，风景集中、节奏相对轻松。",
    itinerary: "波密 -> 来古 -> 南迦巴瓦",
    pricing: { "自由行": 15420 },
    cautions: ["自由行按行程天数核车司", "桃花季与旺季资源更紧"]
  },
  {
    id: "BC-01",
    name: "探索生命的力量",
    liveMatchKeywords: ["探索生命的力量", "遇见桃花与冰川"],
    line: "冰川环线",
    route: "波波来来波达达",
    destination: "glacier",
    destinationLabel: "林芝 / 冰川",
    destinationPriority: "core",
    destinations: ["林芝", "波密", "来古", "南迦巴瓦"],
    nights: 7,
    forms: ["主题团", "私享管家"],
    tags: ["自然", "经典", "冰川", "桃花", "高景观"],
    intensity: "medium",
    familyFriendly: true,
    elderFriendly: false,
    foreignerReady: true,
    seasonMonths: [3, 4, 5, 6, 7, 8, 9, 10],
    description: "林芝高景观重磅线，适合看桃花、冰川、雪山的客群。",
    itinerary: "波密 -> 来古 -> 波密 -> 南迦巴瓦",
    pricing: { "主题团": 16800, "私享管家": 18600 },
    cautions: ["外籍客人需提前核验资质与证照", "春季档期要尽早锁资源"]
  },
  {
    id: "BC-03",
    name: "探访莲花秘境",
    liveMatchKeywords: ["探访莲花秘境"],
    line: "冰川环线",
    route: "波波墨波达",
    destination: "glacier",
    destinationLabel: "林芝 / 冰川",
    destinationPriority: "edge",
    destinations: ["林芝", "波密", "墨脱", "南迦巴瓦"],
    nights: 5,
    forms: ["自由行"],
    tags: ["自然", "小众", "墨脱", "风景"],
    intensity: "high",
    familyFriendly: false,
    elderFriendly: false,
    foreignerReady: true,
    seasonMonths: [4, 5, 6, 7, 8, 9, 10],
    description: "更小众、更有记忆点，适合明确想走墨脱方向的客人。",
    itinerary: "波密 -> 墨脱 -> 波密 -> 南迦巴瓦",
    pricing: { "自由行": 16200 },
    cautions: ["不适合老人和低耐受客群", "需重点沟通路况和转场体验"]
  },
  {
    id: "LS-02",
    name: "雪山圣湖布达拉",
    liveMatchKeywords: ["雪山圣湖布达拉"],
    line: "拉萨环线",
    route: "达达巴巴拉拉拉",
    destination: "lhasa",
    destinationLabel: "拉萨 / 藏文化",
    destinationPriority: "core",
    destinations: ["南迦巴瓦", "巴松措", "拉萨"],
    nights: 6,
    forms: ["主题团", "私享管家"],
    tags: ["自然", "人文", "经典", "圣湖", "首访西藏"],
    intensity: "medium",
    familyFriendly: true,
    elderFriendly: true,
    foreignerReady: true,
    seasonMonths: [3, 4, 5, 6, 7, 8, 9, 10],
    description: "雪山、圣湖、布宫认知最完整的西藏经典款。",
    itinerary: "南迦巴瓦 -> 巴松措 -> 拉萨",
    pricing: { "主题团": 16200, "私享管家": 18200 },
    cautions: ["布宫等核心资源需预约", "异地接送机会增加车司管天数"]
  },
  {
    id: "LS-05",
    name: "遇见圣湖与圣城",
    liveMatchKeywords: ["遇见圣湖与圣城"],
    line: "拉萨环线",
    route: "巴巴巴拉拉",
    destination: "lhasa",
    destinationLabel: "拉萨 / 藏文化",
    destinationPriority: "core",
    destinations: ["巴松措", "拉萨"],
    nights: 5,
    forms: ["自由行"],
    tags: ["自由行", "自然", "人文", "轻松"],
    intensity: "light",
    familyFriendly: true,
    elderFriendly: true,
    foreignerReady: true,
    seasonMonths: [4, 5, 6, 7, 8, 9, 10],
    description: "偏自由节奏的圣湖圣城组合，适合想保留更多自主安排的客人。",
    itinerary: "巴松措 -> 拉萨",
    pricing: { "自由行": 14900 },
    cautions: ["自由行不含管家", "接送机与城市预约需提早规划"]
  },
  {
    id: "ML-03",
    name: "天人之际",
    liveMatchKeywords: ["天人之际"],
    line: "梅里环线",
    route: "奔奔梅梅香",
    destination: "meili",
    destinationLabel: "梅里 / 三江",
    destinationPriority: "core",
    destinations: ["奔子栏", "梅里", "香格里拉"],
    nights: 5,
    forms: ["自由行", "主题团"],
    tags: ["自然", "梅里", "经典", "均衡"],
    intensity: "medium",
    familyFriendly: true,
    elderFriendly: false,
    foreignerReady: false,
    seasonMonths: [1, 2, 3, 4, 5, 9, 10, 11, 12],
    description: "梅里方向里接受度很高的一条，景观强，节奏比超长线更友好。",
    itinerary: "奔子栏 -> 梅里 -> 香格里拉",
    pricing: { "自由行": 14600, "主题团": 15600 },
    cautions: ["冬季版本和常规版本不同", "高海拔适应要单独判断"]
  },
  {
    id: "ML-01",
    name: "穿越三江并流",
    liveMatchKeywords: ["穿越三江并流"],
    line: "梅里环线",
    route: "石石丙丙茨梅香丽",
    destination: "meili",
    destinationLabel: "梅里 / 三江",
    destinationPriority: "core",
    destinations: ["石月亮", "丙中洛", "茨中", "梅里"],
    nights: 8,
    forms: ["主题团", "私享管家"],
    tags: ["自然", "长线", "经典", "重磅"],
    intensity: "high",
    familyFriendly: false,
    elderFriendly: false,
    foreignerReady: false,
    seasonMonths: [1, 2, 3, 4, 5, 9, 10, 11, 12],
    description: "三江并流重磅经典线，适合明确想把云南段一次吃透的客人。",
    itinerary: "石月亮 -> 丙中洛 -> 茨中 -> 梅里 -> 香格里拉 -> 丽江",
    pricing: { "主题团": 18800, "私享管家": 21200 },
    cautions: ["行程长、转场多", "更适合体力和时间都比较充足的客人"]
  },
  {
    id: "SG-01",
    name: "回到远方的家",
    liveMatchKeywords: ["回到远方的家"],
    line: "香格里拉环线",
    route: "丽丽塔塔绿绿",
    destination: "shangri-la",
    destinationLabel: "香格里拉 / 亚丁",
    destinationPriority: "core",
    destinations: ["丽江", "塔城", "绿谷"],
    nights: 6,
    forms: ["自由行", "主题团", "私享管家"],
    tags: ["轻松", "度假", "自然", "家庭友好"],
    intensity: "light",
    familyFriendly: true,
    elderFriendly: true,
    foreignerReady: false,
    seasonMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    description: "很适合首访云南段、又不想太辛苦的客户，综合接受度很高。",
    itinerary: "丽江 -> 塔城 -> 绿谷",
    pricing: { "自由行": 12800, "主题团": 13800, "私享管家": 15600 },
    cautions: ["更偏松弛度假感，卖点不在极致大景", "涉及三店接送机有豁免规则"]
  },
  {
    id: "SG-02",
    name: "亚丁的远山",
    liveMatchKeywords: ["亚丁的远山", "初探亚丁三神山"],
    line: "香格里拉环线",
    route: "丽香香亚亚亚",
    destination: "shangri-la",
    destinationLabel: "香格里拉 / 亚丁",
    destinationPriority: "edge",
    destinations: ["丽江", "香格里拉", "亚丁"],
    nights: 6,
    forms: ["主题团", "私享管家"],
    tags: ["自然", "神山", "摄影", "亚丁"],
    intensity: "medium",
    familyFriendly: false,
    elderFriendly: false,
    foreignerReady: false,
    seasonMonths: [1, 2, 3, 4, 5, 9, 10, 11, 12],
    description: "适合冲着亚丁神山和高原风景来的客人。",
    itinerary: "丽江 -> 香格里拉 -> 亚丁",
    pricing: { "主题团": 15200, "私享管家": 17300 },
    cautions: ["高海拔和景区步行强度要前置沟通"]
  },
  {
    id: "PE-01",
    name: "滇南漫时光",
    liveMatchKeywords: ["滇南漫时光", "探寻美好"],
    line: "普洱",
    route: "普普普普",
    destination: "puer",
    destinationLabel: "昆明 / 普洱",
    destinationPriority: "core",
    destinations: ["普洱"],
    nights: 4,
    forms: ["自由行", "主题团"],
    tags: ["轻松", "美食", "咖啡", "茶文化", "度假"],
    intensity: "light",
    familyFriendly: true,
    elderFriendly: true,
    foreignerReady: false,
    seasonMonths: [1, 2, 3, 4, 5, 10, 11, 12],
    description: "适合想要松弛感、茶咖啡体验和在地生活方式的客人。",
    itinerary: "普洱在地度假",
    pricing: { "自由行": 9800, "主题团": 10800 },
    cautions: ["更偏生活方式体验，不是雪山大景产品"]
  }
];

export const SALES_POLICY_SUMMARY = `
1. 优先推荐标品，轻微变形可以在标品基础上调整；改动过大再转定制。
2. 产品形态分为自由行、私享管家、主题团，不同形态价格与儿童规则不同。
3. 自由行一般不含管家，车司按行程天数核算；私享/主题团会受到接送机时间影响。
4. 儿童价格需要看年龄段；如果年龄未明确，先给区间估算并提醒销售继续确认。
5. 价格是销售预估，不替代正式核价，最终仍需以资源、房型、节假日、季节、活动和执行版本为准。
`;

export const DESTINATION_WORDS = [
  { key: "glacier", label: "林芝 / 冰川", words: ["林芝", "波密", "来古", "南迦巴瓦", "墨脱", "冰川", "桃花", "百巴"] },
  { key: "lhasa", label: "拉萨 / 藏文化", words: ["拉萨", "布达拉宫", "大昭寺", "色拉寺", "巴松措", "乃朗", "日喀则"] },
  { key: "meili", label: "梅里 / 三江", words: ["梅里", "三江", "丙中洛", "茨中", "石月亮", "怒江", "奔子栏"] },
  { key: "shangri-la", label: "香格里拉 / 亚丁", words: ["香格里拉", "亚丁", "丽江", "塔城", "泸沽湖", "神山"] },
  { key: "puer", label: "昆明 / 普洱", words: ["普洱", "昆明", "景迈", "咖啡", "茶山", "滇南"] }
];
